//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzvrseneUsluge
    {
        public int IzvrseneUslugeID { get; set; }
        public Nullable<int> ServisID { get; set; }
        public Nullable<int> UslugaID { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Usluge Usluge { get; set; }
    }
}
