//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        public Korisnici()
        {
            this.IzvrseneUsluge = new HashSet<IzvrseneUsluge>();
            this.Racun = new HashSet<Racun>();
            this.UgradjeniDijelovi = new HashSet<UgradjeniDijelovi>();
            this.Vozilo = new HashSet<Vozilo>();
        }
    
        public int ServisID { get; set; }
        public string ImeKorisnika { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Status { get; set; }
        public string LozinkaHash { get; set; }
        public string LozinkaSalt { get; set; }
        public Nullable<int> SalonID { get; set; }
    
        public virtual ICollection<IzvrseneUsluge> IzvrseneUsluge { get; set; }
        public virtual SalonServis SalonServis { get; set; }
        public virtual ICollection<Racun> Racun { get; set; }
        public virtual ICollection<UgradjeniDijelovi> UgradjeniDijelovi { get; set; }
        public virtual ICollection<Vozilo> Vozilo { get; set; }
    }
}
