//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Vozilo = new HashSet<Vozilo>();
        }
    
        public int ModelID { get; set; }
        public Nullable<int> ProizvodjacID { get; set; }
        public string Naziv { get; set; }
        public string VrstaModela { get; set; }
        public Nullable<int> Kolicina { get; set; }
    
        public virtual Proizvodjac Proizvodjac { get; set; }
        public virtual ICollection<Vozilo> Vozilo { get; set; }
    }
}
