//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NacinPlacanja
    {
        public NacinPlacanja()
        {
            this.Racun = new HashSet<Racun>();
        }
    
        public int PlacanjeID { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<Racun> Racun { get; set; }
    }
}
