//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarudzbaStavke
    {
        public int NarudzbaStavkaID { get; set; }
        public Nullable<int> NarudzbaID { get; set; }
        public Nullable<int> VoziloID { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<int> DijeloviID { get; set; }
    
        public virtual Dijelovi Dijelovi { get; set; }
        public virtual Narudzba Narudzba { get; set; }
        public virtual Vozilo Vozilo { get; set; }
    }
}
