//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzba
    {
        public Narudzba()
        {
            this.NarudzbaStavke = new HashSet<NarudzbaStavke>();
        }
    
        public int NarudzbaID { get; set; }
        public Nullable<int> KupacID { get; set; }
        public string BrojNarudzbe { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Otkazano { get; set; }
    
        public virtual Kupci Kupci { get; set; }
        public virtual ICollection<NarudzbaStavke> NarudzbaStavke { get; set; }
    }
}
