//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodjac
    {
        public Proizvodjac()
        {
            this.Model = new HashSet<Model>();
        }
    
        public int ProizvodjacID { get; set; }
        public string NazivProizvodjaca { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Model> Model { get; set; }
    }
}
