//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalonServis
    {
        public SalonServis()
        {
            this.Korisnici = new HashSet<Korisnici>();
        }
    
        public int SalonID { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public string Sjedište { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Korisnici> Korisnici { get; set; }
    }
}
